name: Generate Stats Images

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Stats Images
        run: |
          mkdir -p generated
          # Baixa o Card de Estatísticas Gerais
          curl -o ./generated/overview.svg "https://github-readme-stats.vercel.app/api?username=nathatargino&theme=highcontrast&show_icons=true"
          # Baixa o Card de Linguagens
          curl -o ./generated/languages.svg "https://github-readme-stats.vercel.app/api/top-langs?username=nathatargino&layout=compact&langs_count=8&theme=highcontrast"

      - name: Push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update stats cards" || exit 0
          git push
