name: Generate Stats Images

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Stats Card
        uses: vn7n24fzkq/github-readme-stats-action@v1
        with:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          THEME: highcontrast 
          SHOW_ICONS: true

      - name: Push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p generated # Garante que a pasta existe
          # Move os arquivos para a pasta que o seu README espera
          mv github-stats.svg ./generated/overview.svg || true
          mv top-langs.svg ./generated/languages.svg || true
          git add .
          git commit -m "Update stats cards" || exit 0
          git push
